services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "uddyog"
      POSTGRES_PASSWORD: "769ec7854db3636f0594d0157e4621fe"
      POSTGRES_DB: "uddyogDB"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
